### ISSUE TITLE
Add verbose mode

### ISSUE THREAD

**Issue by ThatsNasu** [bitbitedev/OpenNetLib#53]
I had the case, where one of my exceptions just got eaten by the lib, which from a design standpooint is fine, but it gave me a headache while debugging, since i did not get any output of it

Steps to fix:
- [ ] Add a verbose mode that is active by default and togglable

**Comment by netcodedev** [comment]
This has been resolved in version 2.0.0
You can now set the `Server` `Client` and `IOHandler` into verbose mode.
This will print the stacktrace of occuring exceptions.
You need to set the verbose mode on each of the classes individually, but static:
```java
IOHandler.setVerbose(true);
```
